### ISSUE TITLE
New build of owntone failing on jenkins

### ISSUE THREAD

**Issue by aptalca** [linuxserver/docker-daapd#50]
Hi @BernsteinA 
Just a heads up, the builds for the new version of Owntone are failing on jenkins: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-daapd/activity

I'm gonna pause the external trigger for now. Let me know when you get a chance to look into it and we'll enable the triggers after it's fixed.

Thanks

**Comment by BernsteinA** [comment]
Thanks. I’ll see if I can take a look this weekend

**Comment by mikepayne02** [comment]
Hey, I think I may have found the issue just by looking at the Jenkins build log:

https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-daapd/detail/master/99/pipeline/131#step-146-log-1872

`mv: cannot stat '/tmp/daapd-build/etc/forked-daapd.conf': No such file or directory`

The configuration file is now called `owntone.conf` instead of `forked-daapd.conf` Therefore the move command doesn't know where the file is and the docker build fails. 


Not sure if this would fix it and I'm not well-equipped enough to test this myself, but changing this line in the Dockerfile could fix the build errors.
https://github.com/linuxserver/docker-daapd/blob/482a557c93122ccfaf99d9ca1fab471805aec19c/Dockerfile#L105
Change to:
`mv /tmp/daapd-build/etc/owntone.conf /tmp/daapd-build/etc/owntone.conf.orig`

Although this may screw up other parts of the application that read the conf file.

**Comment by dhutchison** [comment]
Hey @BernsteinA, did you get a chance to take a look at this? If not I'll try give it a go over the next few days

**Comment by BernsteinA** [comment]
@dhutchison no sorry I didn't -- current image is working fine for my purposes

Instuctions to test builds without pushing to jenkins are in the readme here: https://github.com/linuxserver/docker-daapd/blob/master/README.md#building-locally
